### ISSUE TITLE
Memory usage increases over time

### ISSUE THREAD

**Issue by ingrid-z** [MatrixDJ96/EZBlocker2#10]
once start EZBlocker2. it keeps consuming memory over time.
No matter playing music or not.

task manager screenshot:
![2](https://user-images.githubusercontent.com/22465481/37695132-e2041932-2d07-11e8-81ce-286ad4021ce7.png)

**Comment by MatrixDJ96** [comment]
commit e671b84 should fixed this problem

**Comment by ingrid-z** [comment]
> how long has this taken?

increase 0.2MB/sec, so it took about 32mins.
appreciate your efforts. 😃

**Comment by MatrixDJ96** [comment]
Fixed
