### ISSUE TITLE
Radio and Friends Activity not working

### ISSUE THREAD

**Issue by Sorrizaum** [MatrixDJ96/EZBlocker2#12]
When Block Ads is tickled the Radio of a artist and friend's activity will not work. When disabled, both are working.

**Comment by Sorrizaum** [comment]
[EZBlocker2.log](https://github.com/MatrixDJ96/EZBlocker2/files/2103350/EZBlocker2.log)

**Comment by MatrixDJ96** [comment]
Block Ads could block some Spotify "features"
