### ISSUE TITLE
Error: Invalid OAuth Token

### ISSUE THREAD

**Issue by fellipecorr** [MatrixDJ96/EZBlocker2#13]
Hello,
My old Ezblocker (1) stoped working today, and when I found and install the ezblocker2 it just say "Error: Invlaid OAuth Token" and, of course, doesn't work. Is there something I can do?
![20180720153720](https://user-images.githubusercontent.com/5119849/43005450-2ee976f4-8c33-11e8-9693-1d5cff626835.png)
Thank you

**Comment by Merrit** [comment]
Having the same issue.

**Comment by DefecateRainbows** [comment]
Exact same situation as fellipecorr... From issues in the first EZBlocker repo, you can see that the first EZBlocker is failing for the same reason.

**Comment by fellipecorr** [comment]
I guess spotify block the extraction of metadata of current song. Maybe if another program could access to this metadata, Ezblocker could acces that third program.

**Comment by MatrixDJ96** [comment]
I'll check this problem
Thanks for your report

**Comment by MatrixDJ96** [comment]
https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/

**Comment by fellipecorr** [comment]
So, does it have solution? I see windows itself can access to metadata (is about getting metadata and muting the ads, right?)
![imagen](https://user-images.githubusercontent.com/5119849/43044583-0a3ccb18-8da9-11e8-97f3-044e6ac99892.png)

**Comment by fellipecorr** [comment]
So, does it have solution? I see windows itself can access to metadata (is about getting metadata and muting the ads, right?)
![Uploading imagen.png…]()

**Comment by MatrixDJ96** [comment]
Windows doesn't use metadata from Spotify..
What you see is only the "Title" property of Spotify application set when you play a song

Here an example
![immagine](https://user-images.githubusercontent.com/8330294/43047438-80da50a0-8dd7-11e8-8570-a32e35478f0d.png)

**Comment by MatrixDJ96** [comment]
EZBlocker is "working" because it detects spotify ads when the (spotify) title is without " - ".
![immagine](https://user-images.githubusercontent.com/8330294/43067137-c2536014-8e66-11e8-98f4-9b1b8db2b479.png)

**Comment by fellipecorr** [comment]
Man, that's clever. Please erase that post, I don't wanna de spotify people to read this and change the title bar, haha ;)

**Comment by MatrixDJ96** [comment]
I'm back with new project
https://youtu.be/LzpW_rlw0Qc

**Comment by MatrixDJ96** [comment]
This is a new method (using official Spotify API) to get metadata of playing song
No Spotify modification!

**Comment by Merrit** [comment]
That looks great! Looking forward to trying it out.

**Comment by MatrixDJ96** [comment]
Try new (beta) version:
https://github.com/MatrixDJ96/EZBlocker2/releases/tag/v2.1.3.0

**Comment by MatrixDJ96** [comment]
Discussion here: https://github.com/MatrixDJ96/EZBlocker2/issues/15
