### ISSUE TITLE
Version 2.1.3.x

### ISSUE THREAD

**Issue by MatrixDJ96** [MatrixDJ96/EZBlocker2#15]
Post here problems about EZBlocker 2 v2.1.3.x

**Comment by MatrixDJ96** [comment]
To use this version (and newer) you must login into your Spotify account and you must connect (accept) EZBlocker 2 to your account

**Comment by MatrixDJ96** [comment]
@wnervhq try new version
https://github.com/MatrixDJ96/EZBlocker2/releases/tag/v2.1.3.1

**Comment by wnervhq** [comment]
Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.NotSupportedException: WebClient no admite operaciones de E/S simultáneas.
   en System.Net.WebClient.ClearWebClientState()
   en System.Net.WebClient.DownloadDataAsync(Uri address, Object userToken)
   en System.Net.WebClient.DownloadDataTaskAsync(Uri address)
   en EZBlocker2.Spotify.WebAPI.<GetStatus>d__47.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3160.0 built by: NET472REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
EZBlocker2
    Versión del ensamblado: 2.1.3.1
    Versión Win32: 2.1.3.1
    Código base: file:///D:/Program%20Files%20(x86)/EZBlocker/EZBlocker2.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3160.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3160.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Newtonsoft.Json
    Versión del ensamblado: 11.0.0.0
    Versión Win32: 11.0.1.21818
    Código base: file:///D:/Program%20Files%20(x86)/EZBlocker/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3160.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3160.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.resources.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by MatrixDJ96** [comment]
New version released!
Now it should be stable

**Comment by Primeey** [comment]
Can't it save the authorization? Because now everytime I open EZBlocker 2 it always opens a webpage to authorize.

**Comment by MatrixDJ96** [comment]
I know but for now this is the only method
