### ISSUE TITLE
Host file entries interfere with browsing experience

### ISSUE THREAD

**Issue by Sogolumbo** [MatrixDJ96/EZBlocker2#21]
The `0.0.0.0 www.googleadservices.com` entry in the host file (C:\Windows\System32\drivers\etc\hosts) interferes with the browser experience. When searching for products on google the results that are marked as ads are blocked. 
![image](https://user-images.githubusercontent.com/33571916/45882294-0162a000-bdae-11e8-8f6d-4bbc878dce19.png)

**Comment by Sogolumbo** [comment]
Just a little update: I have removed the entry from my host file and the ad-muting is working fine. I sometimes want to see these entries so it would be great if EZBlocker didn't show a annoying message box everytime I open it. (It is running on autostart).

**Comment by MatrixDJ96** [comment]
Blocking addresses in hosts file should not be used...
I suggest you to use only ad-muting
