### ISSUE TITLE
Option to disable the center window dialog

### ISSUE THREAD

**Issue by thegamerx1** [MatrixDJ96/EZBlocker2#27]
Switching between virtual desktops `win + ctrl + left/right` makes ezblocker2 to show that annoying window

**Comment by DerRockWolf** [comment]
What annoying window?

**Comment by thegamerx1** [comment]
Im not using this program anymore but its a window that asks if you want to center the EZBlocker2 window to the screen

**Comment by DerRockWolf** [comment]
Now I know what you talking about :)
But for me it is only popping up when EZBlocker is in foreground.

**Comment by MatrixDJ96** [comment]
Like @DerRockWolf said that `annoying window` appears only when EZBlocker 2 is in foregroud

**Comment by thegamerx1** [comment]
It does only appear in foreground but is annoying having to unfocus the ezblocker2 window  to change between virtual desktops

**Comment by DerRockWolf** [comment]
@thegamerx1 why is that a problem? Just leave EZBlocker in the background and forget about it...
