### ISSUE TITLE
Spotify seems to be always mute

### ISSUE THREAD

**Issue by Liryna** [MatrixDJ96/EZBlocker2#3]
Hi,

My Spotify seems now to be always mute. I have tried to reinstall Spotify, remove ezblocker but I can still not listen a sound. The play show the music played, I can hear other applications (YouTube, Spotify web, vlc...) but impossible to get Spotify app working 😢 how can I check if this does not come from an ezblocker configuration that refuse to reset ?

Thanks in advance,

**Comment by MatrixDJ96** [comment]
Check in system volumes if spotify is muted or not

**Comment by Liryna** [comment]
Sorry again for disturbing you, you are right, it was simply the system volume of spotify app 👍 
Thank you
