### ISSUE TITLE
ERROR 429 (Too many request)

### ISSUE THREAD

**Issue by MatrixDJ96** [MatrixDJ96/EZBlocker2#31]
Hello mates,
I want to post this issue because recently a lot of EZBlocker's users have received this annoying error.

_Here directly from **Spotify** documentation_

> ### Rate Limiting
> 
> Rate Limiting enables Web API to share access bandwidth to its resources equally across all users.
> 
> Rate limiting is applied as per application based on Client ID, and regardless of the number of users who use the application simultaneously.
> 
> To reduce the amount of requests, use endpoints that fetch multiple entities in one request. For example: If you often request single tracks, albums, or artists, use endpoints such as Get Several Tracks, Get Several Albums or Get Several Artists, instead.
> 
> Note: If Web API returns status code 429, it means that you have sent too many requests. When this happens, check the Retry-After header, where you will see a number displayed. This is the number of seconds that you need to wait, before you try your request again.

For all users that are using EZBlocker 2 this is a really bad news because to check Spotify status, EZBlocker makes a request every 500ms to the **Web API**...

This means that EZBlocker couldn't detect current playing song (and so if you are playing ads) correctly

To solve this `issue` I'll make a guide on how to create a personal EZBlocker with custom **Client ID**.

Thanks for your attention :)

**Comment by LittleStinky123** [comment]
Which redirect URIs need to be registered with spotify so I don't get a "INVALID_CLIENT: Invalid redirect URI" error?

**Comment by Spacelord09** [comment]
#37

**Comment by pizzadudez** [comment]
@LittleStinky123 did you manually change the clientID and recompiled the project or did you expose it in a settings file aswell?

**Comment by LittleStinky123** [comment]
@pizzadudez I only did the changes I mentioned in https://github.com/MatrixDJ96/EZBlocker2/issues/37#issuecomment-585416600 I had to recompile it with my changes, the most time consuming part was setting up a spotify developer account anyway.

**Comment by pizzadudez** [comment]
@LittleStinky123 I didn't see your comment on #37 before writing. I was wondering mostly if someone has already moved the spotify client credentials in a settings file to make the process easier for everyone using this app. I don't currently have the setup to recompile it but I'll get the necessary dependecies and look into maybe adding this feature I mentioned.

**Comment by zogo3000** [comment]
Just wondering if you ever did do a tutorial - trying to follow the comments but I they're spread out over diff issues and I'm not the most apt regardless
