### ISSUE TITLE
Make the success page close itself automatically

### ISSUE THREAD

**Issue by johnathanmitri** [MatrixDJ96/EZBlocker2#33]
adding `<SCRIPT>
    window.close();
</SCRIPT>`
to the body of the authorization page html will make it close itself

This would be nice because the tab popping up is kind of annoying

**Comment by MatrixDJ96** [comment]
You couldn't use this code to close window

![immagine](https://user-images.githubusercontent.com/8330294/72971827-ab9b6f00-3dca-11ea-8fea-c0804220fd94.png)
