### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by Fruitybrute** [MatrixDJ96/EZBlocker2#35]
[EZBlocker2.log](https://github.com/MatrixDJ96/EZBlocker2/files/4141620/EZBlocker2.log)
Can't authorize EZBlocker2 with Spotify. I refresh the page to no avail.

**Comment by Spacelord09** [comment]
For me it works fine. Probably #31 ?

**Comment by MatrixDJ96** [comment]
No more info, closed
