### ISSUE TITLE
Spotify is in private session

### ISSUE THREAD

**Issue by Paoloc99** [MatrixDJ96/EZBlocker2#37]
When i open EZBlocker2, a web page opens on my browser but the connection fails with the error: "This site can’t be reached".

**Comment by Spacelord09** [comment]
#31

**Comment by Paoloc99** [comment]
So, have i to wait that guide?

**Comment by Spacelord09** [comment]
I think you need to wait.

**Comment by LittleStinky123** [comment]
There are so few steps that it is hardly worth a guide:

1. Create a spotify app
2. Create a client secret
3. Register these redirect URIs(Some may be superfluous):
3.1 http://127.0.0.1:5515/
3.2 http://127.0.0.1:5515/authorization/
3.3 http://127.0.0.1:5515/authorization/&response_type=code
4. Change ClientID in WebAPI.cs to your app's clientID
5. Change Authorization in WebAPI.cs to "Basic " + the base64 encoded string of the concatenated clientID:clientSecret
6. Compile it as release with Visual Studio and enjoy

**Comment by pizzadudez** [comment]
If anyone is interested I exposed the credentials to be changed from the .ini config file. You can get the binary from [my fork](https://github.com/pizzadudez/EZBlocker2/releases) for now until the pr gets approved.

**Comment by MatrixDJ96** [comment]
Check pull request #44
