### ISSUE TITLE
Merge new release?

### ISSUE THREAD

**Issue by guillemglez** [MatrixDJ96/EZBlocker2#39]
Eric Zhang just released an update (v1.7.4): https://github.com/Xeroday/Spotify-Ad-Blocker/releases/tag/v1.7.4.0

Can someone assess whether it's worth merging?

**Comment by guillemglez** [comment]
Now [1.7.5](https://github.com/Xeroday/Spotify-Ad-Blocker/releases/tag/v1.7.5.0)...

**Comment by MatrixDJ96** [comment]
EZBlocker couldn't be merged because they use different hooking method
