### ISSUE TITLE
Add support for multiple playback outputs

### ISSUE THREAD

**Issue by autoelk** [MatrixDJ96/EZBlocker2#41]
When it mutes or unmutes spotify for one audio playback output, it should mute or unmute it for all of them so that you are able to switch between headphones and speakers without having to manually mute or unmute.

**Comment by Spacelord09** [comment]
Hey. The blocker is muting the software via the windows sound system.

**Comment by lukefly2** [comment]
I know that, but is it possible to mute spotify across multiple output devices using the windows sound system?

**Comment by Spacelord09** [comment]
Its automarically muted on all output devices.

**Comment by kadeve** [comment]
I dont understand what you are trying achieve but maybe install virtual audio cable ? so you can manage your multiple outputs better. I use a DAC AMP to switch between output sources rather than software. You can easily DIY circuit to redirect sound to multiple outputs
