### ISSUE TITLE
Virus question...?

### ISSUE THREAD

**Issue by damanteg** [MatrixDJ96/EZBlocker2#43]
Hi I just wanted to make sure the ezblocker 2 isnt a virus or keylogger or something sketchy right?

Thanks

**Comment by damanteg** [comment]
hi the ezblocker 2 app i have installed is failing to block ads they mute but still play?

**Comment by DerRockWolf** [comment]
It's not a virus nor a keylogger. If you are really concerned read the code.

Regarding your second question: Just read the README.md there you will find all the information.
To elaborate that a little: EZBlocker2 can only block banner ads, as far as I know (done with hosts patches).
