### ISSUE TITLE
Logon doesn't work

### ISSUE THREAD

**Issue by ghost** [MatrixDJ96/EZBlocker2#49]
Start at logon doesn't work, and it makes me open this site every single time http://127.0.0.1:5515/authorization/?code=AQCNofci_BQbdWNJjwbiZOWwwX8T5uVGOBl5q82SifrYCQfIrhf4tjjfFfzncthQLQvARX1ip0dbs35QPuKeFUlEHcMdb6v7NpYqRuq4oq8T-VA4e-Sfx_-aSJY785Phapc3lWjDOWXjSsaniL7K3If5T7LHTY2XbdBEnlWnGzTCrJdNB0qWQ7LLgMNQG3lLwnrta1I0Zk7eNdTFyGSc76fJXsQl. 
Pls fix ASAP

**Comment by Spacelord09** [comment]
Thats not a bug.. Its going to log you into your account.. Just follow the steps on the site

**Comment by ghost** [comment]
Oh ok. But the site doesn't show anything, just a blank page. I also have to manually run it every time instead of it starting automatically.

**Comment by Spacelord09** [comment]
Do you have a popup blocker?

**Comment by ayaaop** [comment]
Hey, I've had the same issue, you might want to run Ezblocker as an administator, so the hosts patches will apply to the system
