### ISSUE TITLE
Block ads option doesn't seem to be working correctly..

### ISSUE THREAD

**Issue by JourneyOver** [MatrixDJ96/EZBlocker2#5]
Using the "block ads" option from ezblocker2 doesn't seem to either pull in the full host edit that it should or something else is going on, as upon using it it'll still allow ads through on spotify. If I go and manually edit my host file to use the same host edits* from [FadeMind repo](https://github.com/FadeMind/hosts.extras/blob/master/Spotify-Ad-free/hosts) for spotify then spotify will no longer have any ads whats so ever. Any idea on why this is happening?

* That ezblocker2 is supposedly pulling it's host edits from..

**Comment by MatrixDJ96** [comment]
I don't use FadeMind repo because some servers that are needed to play music

**Comment by JourneyOver** [comment]
well you was crediting 

> Steven Black for hosts patches

 
which is the one that's on fademinds repo so I thought you was using it. *which btw I haven't had any issues using.

Either way your host patch doesn't block ads at all, as ads still get through if I use your "block ads" option so just thought I'd give you a heads up.

**Comment by MatrixDJ96** [comment]
Check this out:
https://github.com/CHEF-KOCH/Spotify-Ad-free/issues/2

And this:
https://github.com/CHEF-KOCH/Spotify-Ad-free/blob/master/do%20not%20block.txt

**Comment by JourneyOver** [comment]
Well I don't use the web player nor do I use the phone app, so I can't really say much for either of those. I use the desktop app and haven't had a single issue though while using fademinds host edits for spotify and I've been using them ever since he created them.

Anyways like I said before just wanted to give you a heads up, but you should either remove the whole "block ads" option or fix it or at least change the option name to something that actually reflects what it does because as right now it's just misleading since it doesn't do what the option actually says it does.

**Comment by MatrixDJ96** [comment]
Check with new version

**Comment by MatrixDJ96** [comment]
Try this:
[EZBlocker2 TEST.zip](https://github.com/MatrixDJ96/EZBlocker2/files/1864522/EZBlocker2.TEST.zip)

**Comment by JourneyOver** [comment]
I actually forgot all about this, honestly just going to close it as I have since stopped using this as I (dunno why I didn't think about this earlier) have no need for it with my host edits..
