### ISSUE TITLE
bug #1: the last second of ads are not muted

### ISSUE THREAD

**Issue by mkeroppi** [MatrixDJ96/EZBlocker2#8]
Seems to came back but much less than 1 second now.

**Comment by MatrixDJ96** [comment]
This no longer depends on EZBlocker 2
The spotify local server is queried every 100 ms and based on the information received the program mutes the ads

**Comment by mkeroppi** [comment]
That's too bad.  I think it's more than 100ms though.

**Comment by MatrixDJ96** [comment]
Closed #15
